(* begin-documentation-node
###############
  Development
###############


.. toctree::
   :maxdepth: 2
   :caption: Development:
   :hidden:

   ../Build/Simple    <Tutorial.rst>
   ../Examples/Course <Examples.rst>
   ../Oberon/Oberon   <Core.rst>
   ../System/System   <Std.rst>
   ../Mod/Suite   <Sup.rst>
   ../Mod/Vet     <Style.rst>

Development documentation starts here...

https://github.com/io-core/Build/blob/main/Explore.Mod

end-documentation-node *)


(* begin-package-description
### _Package Overview:_
The Doc package manages:
* Generating documentation from Oberon package sources
* Browsing (eventually) Oberon documentation
### _Package Use:_

USAGE:
```
# from external system with python and sphinx

make extract; make clean; make html

```

### _Modules in this package:_
end-package-description *)

(* begin-module-short-description
TODO: provide a package repository explorer.
end-module-short-description *)

(* begin-module-use-description
Module Explore handles:
* Nothing yet. Placeholder.

end-module-use-description *)
MODULE Explore; 
  IMPORT SYSTEM;

  CONST 

  TYPE 

  VAR 

  (* begin-section-description
## ---------- Generate Documentation
  end-section-description *)

  (* begin-procedure-description
---
**Foo** is a placeholder
  end-procedure-description *)
  PROCEDURE Foo;
  BEGIN 
  END Foo;



END Explore.
