(* begin-documentation-node
#############
  Tutorial
#############

Creating a Project
======================

* Create a Package Directory
* Create a Package File
* Create a Module Source File


Compiling Source Code
=======================

* From a command
* From a window
* With a new .sym file
* In a script

Running the Code
================

* from a command

https://github.com/io-core/Build/blob/main/Simple.Mod

end-documentation-node *)


(* begin-module-use-description
Module Simple handles:
* Nothing yet.

end-module-use-description *)
MODULE Simple; 
  IMPORT SYSTEM;

  CONST 

  TYPE 

  VAR 

  (* begin-section-description
## ---------- Generate Documentation
  end-section-description *)

  (* begin-procedure-description
---
**Foo** is a placeholder
  end-procedure-description *)
  PROCEDURE Foo;
  BEGIN 
  END Foo;



END Simple.
